// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: demo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Demo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo) Reset() {
	*x = Demo{}
	mi := &file_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo) ProtoMessage() {}

func (x *Demo) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo.ProtoReflect.Descriptor instead.
func (*Demo) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Demo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Demo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Demo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DemoIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoIdentifier) Reset() {
	*x = DemoIdentifier{}
	mi := &file_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoIdentifier) ProtoMessage() {}

func (x *DemoIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoIdentifier.ProtoReflect.Descriptor instead.
func (*DemoIdentifier) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{1}
}

func (x *DemoIdentifier) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListDemosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Demos         []*Demo                `protobuf:"bytes,1,rep,name=demos,proto3" json:"demos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDemosResponse) Reset() {
	*x = ListDemosResponse{}
	mi := &file_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDemosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDemosResponse) ProtoMessage() {}

func (x *ListDemosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDemosResponse.ProtoReflect.Descriptor instead.
func (*ListDemosResponse) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{2}
}

func (x *ListDemosResponse) GetDemos() []*Demo {
	if x != nil {
		return x.Demos
	}
	return nil
}

type GetDemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Demo          *Demo                  `protobuf:"bytes,1,opt,name=demo,proto3" json:"demo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoResponse) Reset() {
	*x = GetDemoResponse{}
	mi := &file_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoResponse) ProtoMessage() {}

func (x *GetDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoResponse.ProtoReflect.Descriptor instead.
func (*GetDemoResponse) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{3}
}

func (x *GetDemoResponse) GetDemo() *Demo {
	if x != nil {
		return x.Demo
	}
	return nil
}

type CreateDemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemoRequest) Reset() {
	*x = CreateDemoRequest{}
	mi := &file_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemoRequest) ProtoMessage() {}

func (x *CreateDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemoRequest.ProtoReflect.Descriptor instead.
func (*CreateDemoRequest) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDemoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_demo_proto protoreflect.FileDescriptor

const file_demo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"demo.proto\x12\x04demo\x1a\fcommon.proto\"L\n" +
	"\x04Demo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\" \n" +
	"\x0eDemoIdentifier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"5\n" +
	"\x11ListDemosResponse\x12 \n" +
	"\x05demos\x18\x01 \x03(\v2\n" +
	".demo.DemoR\x05demos\"1\n" +
	"\x0fGetDemoResponse\x12\x1e\n" +
	"\x04demo\x18\x01 \x01(\v2\n" +
	".demo.DemoR\x04demo\"I\n" +
	"\x11CreateDemoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\xbe\x01\n" +
	"\vDemoService\x125\n" +
	"\tListDemos\x12\r.common.Empty\x1a\x17.demo.ListDemosResponse\"\x00\x128\n" +
	"\aGetDemo\x12\x14.demo.DemoIdentifier\x1a\x15.demo.GetDemoResponse\"\x00\x12>\n" +
	"\n" +
	"CreateDemo\x12\x17.demo.CreateDemoRequest\x1a\x15.demo.GetDemoResponse\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_demo_proto_rawDescOnce sync.Once
	file_demo_proto_rawDescData []byte
)

func file_demo_proto_rawDescGZIP() []byte {
	file_demo_proto_rawDescOnce.Do(func() {
		file_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)))
	})
	return file_demo_proto_rawDescData
}

var file_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_demo_proto_goTypes = []any{
	(*Demo)(nil),              // 0: demo.Demo
	(*DemoIdentifier)(nil),    // 1: demo.DemoIdentifier
	(*ListDemosResponse)(nil), // 2: demo.ListDemosResponse
	(*GetDemoResponse)(nil),   // 3: demo.GetDemoResponse
	(*CreateDemoRequest)(nil), // 4: demo.CreateDemoRequest
	(*Empty)(nil),             // 5: common.Empty
}
var file_demo_proto_depIdxs = []int32{
	0, // 0: demo.ListDemosResponse.demos:type_name -> demo.Demo
	0, // 1: demo.GetDemoResponse.demo:type_name -> demo.Demo
	5, // 2: demo.DemoService.ListDemos:input_type -> common.Empty
	1, // 3: demo.DemoService.GetDemo:input_type -> demo.DemoIdentifier
	4, // 4: demo.DemoService.CreateDemo:input_type -> demo.CreateDemoRequest
	2, // 5: demo.DemoService.ListDemos:output_type -> demo.ListDemosResponse
	3, // 6: demo.DemoService.GetDemo:output_type -> demo.GetDemoResponse
	3, // 7: demo.DemoService.CreateDemo:output_type -> demo.GetDemoResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_demo_proto_init() }
func file_demo_proto_init() {
	if File_demo_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_proto_goTypes,
		DependencyIndexes: file_demo_proto_depIdxs,
		MessageInfos:      file_demo_proto_msgTypes,
	}.Build()
	File_demo_proto = out.File
	file_demo_proto_goTypes = nil
	file_demo_proto_depIdxs = nil
}
